### ISSUE TITLE
[Composite.Web.Css.Sass] NetworkError: 404 Not Found 

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-Packages#12]
![capture](https://cloud.githubusercontent.com/assets/11037398/11918997/b7f01a28-a6fa-11e5-9441-1ea902dc78a9.PNG)

There is no package preview url:
NetworkError: 404 Not Found - http://docs.composite.net/Composite.Web.Css.Sass?contentOnly=1

but there is: http://www.composite.net/Products/Add-ons/All/Composite.Web.Css.Sass

**Comment by InnaBoitsun** [comment]
Fixed
