### ISSUE TITLE
[Composite.Versioning.ContentVersioning] Compare versions bug

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-Packages#19]
![capture](https://cloud.githubusercontent.com/assets/11037398/12489770/d303e2aa-c026-11e5-8d6e-3eb3c1a35311.PNG)

**Comment by wwwysocki** [comment]
Can't reproduce. Tested on v5 and the latest build. 
ContentVersioning v 2.4.1

Please re-open the issue if you have steps to reproduce the issues.

![versioning-compare-versions](https://cloud.githubusercontent.com/assets/14821915/13104240/9810b2d8-d564-11e5-8aef-5f73779a3d43.png)
