### ISSUE TITLE
[Composite.Forms.FormBuilder] Form validation in IE and FF error when position: fixed

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-Packages#6]
Reproduce: http://demo3.c1.composite.net/About-us/Contact-us - scroll to the end of the page, moment when you see only "Message". Hit Submit.
Expected: scroll to the not filled "Your Name". 
Error: Visually nothing happens in IE (in FF a bit scroll up) because .navbar-fixed-top have position: fixed (actual scroll happens, but not complete - it's not covering height of navbar-fixed-top)

**Comment by InnaBoitsun** [comment]
I thinks that is not a package bug, on that case the specific workaround required for the site where the package is used.

**Comment by aeont** [comment]
simple "kind of" workaround is 

    <script type="text/javascript">
        $(document).ready(function () {
            $('.formbuilder').submit(function (event) {
                $('html,body').scrollTop(0);
            });
        });
    </script>

but it's just part of the story, ideal solution is subscribe to validate event, get position of first error and jump it to there - height of navbar.

**Comment by aeont** [comment]
@InnaBoitsun @mawtex @napernik 

here the right fix - you need change your class name and probably formula - for simplicity I'm just multiply by 2, because in my case label height can be changed dynamically onfocus.

    <script type="text/javascript">
        $(document).ready(function () {
            $('.formbuilder').validate({
                invalidHandler: function (form, validator) {
                    $('html,body').scrollTop($(validator.errorList[0].element).offset().top - ($('.navigation__controllers').height()) * 2);
                }
            });
        });
    </script>
